name: trackhub_home_health
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.4
  sliding_up_panel: ^2.0.0+1
  rounded_loading_button: ^2.1.0
  intl_phone_number_input: ^0.7.0+2
  flutter_styled_toast: 2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  badges: ^2.0.2
  avatar_glow: ^2.0.2
  timeline_tile: ^2.0.0
  page_transition: ^2.0.5
  video_player: 2.3.0
  uuid: 3.0.6
  searchfield: ^0.6.6
  flutter_spinkit: ^5.1.0
  geocoding: ^2.0.4
  flutter_keyboard_visibility: ^5.3.0
  image_picker: ^0.8.5+3
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: Montserrat ExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf

    - family: Montserrat Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf

    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Montserrat SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
